name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android_test_job:
    name: Android Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v3
        with:
          api-level: 33
          script: ./gradlew connectedAndroidTest
      - name: Upload Android Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: android-test-reports
          path: ‘**/build/reports/androidTests/’

  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build